Vagrant.configure("2") do |config|
    (1..2).each do |i|
        config.vm.define "K8S_00#{i}" do |k8s|
            k8s.vm.box = "debian/bullseye64"
            k8s.disksize.size = "30GB"
            k8s.vm.network "public_network", bridge: "en0: Ethernet", ip: "192.168.100.10#{i}"
            k8s.vm.synced_folder "/Volumes/DATA/Tecnologia/GitHub/alexandrerfischer/Projects/Kubernetes/P_K8S/", "/Projects/"
            k8s.vm.provider "virtualbox" do |v|
                v.memory = 2048
                v.cpus = 1
                v.name = "K8S_00#{i}"
            end
        config.vm.provision :shell, :path => "initial-configs.sh"
        config.vm.provision :shell, :path => "initial-docker.sh"
        config.vm.provision :shell, :path => "initial-kubectl.sh"
        config.vm.provision :shell, :path => "initial-helm.sh"
        end
    end
    (1..1).each do |i|
        config.vm.define "RANCHER_00#{i}" do |rancher|
            rancher.vm.box = "debian/bullseye64"
            rancher.disksize.size = "30GB"
            rancher.vm.network "public_network", bridge: "en0: Ethernet", ip: "192.168.100.10#{i + 2}"
            rancher.vm.synced_folder "/Volumes/DATA/Tecnologia/GitHub/alexandrerfischer/Projects/Kubernetes/P_K8S/", "/Projects/"
            rancher.vm.provider "virtualbox" do |v|
                v.memory = 2048
                v.cpus = 1
                v.name = "RANCHER_00#{i}"
            end
        config.vm.provision :shell, :path => "initial-configs.sh"
        config.vm.provision :shell, :path => "initial-docker.sh"
        config.vm.provision :shell, :path => "initial-kubectl.sh"
        config.vm.provision :shell, :path => "initial-helm.sh"
        end
    end
end